# Generated by Django 4.2.28 on 2026-03-01 07:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("chief_judge_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="setup",
                        max_length=20,
                    ),
                ),
                ("current_round", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bib_number", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("leader", "Leader"), ("follower", "Follower")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["bib_number"],
                "unique_together": {("competition", "bib_number")},
            },
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_chief_judge", models.BooleanField(default=False)),
                (
                    "assigned_role",
                    models.CharField(
                        choices=[
                            ("leader", "Leader"),
                            ("follower", "Follower"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judges",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={"ordering": ["-is_chief_judge", "name"],},
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "round_type",
                    models.CharField(
                        choices=[("preliminary", "Preliminary"), ("final", "Final")],
                        max_length=20,
                    ),
                ),
                ("heat_size", models.IntegerField(default=6)),
                ("required_yes_count", models.IntegerField(default=3)),
                ("advancing_count", models.IntegerField(default=0)),
                (
                    "alternate_count",
                    models.IntegerField(choices=[(2, "2"), (3, "3")], default=2),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["competition", "number"],
                "unique_together": {("competition", "number")},
            },
        ),
        migrations.CreateModel(
            name="Heat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followers",
                    models.ManyToManyField(
                        limit_choices_to={"role": "follower"},
                        related_name="follower_heats",
                        to="competitions.competitor",
                    ),
                ),
                (
                    "leaders",
                    models.ManyToManyField(
                        limit_choices_to={"role": "leader"},
                        related_name="leader_heats",
                        to="competitions.competitor",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heats",
                        to="competitions.round",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "number"],
                "unique_together": {("round", "number")},
            },
        ),
        migrations.CreateModel(
            name="PreliminaryScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_score", models.IntegerField()),
                (
                    "calculated_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("alt1", "Alternate 1"),
                            ("alt2", "Alternate 2"),
                            ("alt3", "Alternate 3"),
                            ("no", "No"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("points", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preliminary_scores",
                        to="competitions.competitor",
                    ),
                ),
                (
                    "heat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preliminary_scores",
                        to="competitions.heat",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preliminary_scores",
                        to="competitions.judge",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preliminary_scores",
                        to="competitions.round",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "heat", "competitor", "judge"],
                "unique_together": {("judge", "competitor", "round", "heat")},
            },
        ),
        migrations.CreateModel(
            name="FinalScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("technique_score", models.IntegerField(blank=True, null=True)),
                ("timing_score", models.IntegerField(blank=True, null=True)),
                ("presentation_score", models.IntegerField(blank=True, null=True)),
                ("raw_score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_scores",
                        to="competitions.competitor",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_scores",
                        to="competitions.judge",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_scores",
                        to="competitions.round",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "competitor", "judge"],
                "unique_together": {("judge", "competitor", "round")},
            },
        ),
    ]
